# Generated by Django 3.0.3 on 2020-02-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi.Planet', verbose_name='Название ордена')),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Джедая')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi.Planet', verbose_name='Планета')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя кандидата')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('jedi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedi.Jedi')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi.Planet', verbose_name='Планета')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi.Candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi.Question')),
            ],
            options={
                'unique_together': {('candidate', 'question')},
            },
        ),
    ]
