# Generated by Django 3.0.3 on 2020-02-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi', '0002_auto_20200207_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podavans', to='jedi.Jedi'),
        ),
    ]
